name: Pip

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  build_mac:
    strategy:
      matrix:
        #python-version: ["3.5", "3.8", "3.9"]
        python-version: ["3.9"]

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Update Homebrew
      run: brew update

    - name: Install dependencies
      run: brew install libmad libpng jpeg-turbo SDL2 openal-soft

    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Add requirements
      run: python -m pip install --upgrade wheel setuptools

    - name: Build and install
      run: pip install --verbose .[test]

    - name: Test
      run: pytest

  build_windows:
    strategy:
      matrix:
        #python-version: ["3.5", "3.8", "3.9"]
        python-version: ["3.8"]

    runs-on: windows-latest

    env:
      DIR_MINGW64: C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\x86_64-w64-mingw32
      DIR_ESLIB: .\dev64
      AR: gcc-ar

    steps:
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-python-pip

    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Fetch development libraries
      run: |
        # thanks MCO
        Invoke-WebRequest https://endless-sky.github.io/win64-dev.zip -OutFile win64-dev.zip
        Expand-Archive win64-dev.zip -DestinationPath . -Force
        Remove-Item win64-dev.zip

    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Add requirements
      shell: msys2 {0}
      run: python -m pip install --upgrade wheel setuptools

    - name: specify mingw compiler to setuptools
      run: |
        "[build]`ncompiler=mingw32`n" | Out-File -FilePath setup.cfg

    - name: Build and install
      shell: msys2 {0}
      run: pip install --verbose .[test]

    - name: Test
      shell: msys2 {0}
      run: pytest

  build_linux:
    strategy:
      matrix:
        #python-version: ["3.5", "3.8", "3.9"]
        python-version: ["3.9"]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install dependencies
      run: |
        sudo rm /etc/apt/sources.list.d/* && sudo dpkg --clear-avail
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends libsdl2-dev libpng-dev libjpeg-turbo8-dev libopenal-dev libmad0-dev libglew-dev libgl1-mesa-dev libegl1-mesa-dev libgles2-mesa-dev uuid-dev

    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Add requirements
      run: python -m pip install --upgrade wheel setuptools

    - name: Build and install
      run: pip install --verbose .[test]

    - name: Test
      run: pytest
